FROM golang:1.25-alpine

ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOTOOLCHAIN=auto

RUN apk add --no-cache gcc musl-dev && \
    go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.work ./
COPY apps/gateway/go.mod ./apps/gateway/
COPY apps/engine/go.mod ./apps/engine/
COPY libs/shared/go.mod ./libs/shared/
COPY libs/telemetry/go.mod ./libs/telemetry/

RUN go mod download

CMD ["air"]
